  spring:
    application:
      name: Default Config Dev
  
  eureka:
    instance:
      instance-id: DEV-CONFIG
      prefer-ip-address: true
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:8761/eureka
